<?php

/**
 * Test class for CompleXml_Auth_Result.
 * Generated by PHPUnit on 2010-02-12 at 11:58:36.
 *
 * @group Auth
 */
class CompleXml_Auth_ResultTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var CompleXml_Auth_Result
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CompleXml_Auth_Result(CompleXml_Auth_Result::OK, array());
    }

    public function testGetUser()
    {

    }

    public function testGetStatus()
    {

    }

    public function testIsValid()
    {
        
    }

    public function testGetDate()
    {

    }

    public function testSetDate()
    {

    }
}
